- name: Install Apache web server
  apt:
    name: apache2
    state: present

- name: Copy FinTarget application code
  copy:
    src: /etc/ansible/ansible-playbook/index.html  
    dest: /var/www/html/index.html

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes
