- name: Install Apache web server
  apt:
    name: apache2
    state: present

- name: Copy FinTarget application code
  copy:
    src: /path/to/your/fintarget/code/  
    dest: /var/www/html/

- name: Start Apache service
  service:
    name: apache2
    state: started
    enabled: yes
